### ISSUE TITLE
Missing Docker options after migration

### ISSUE THREAD

**Issue by StefanRother-OTOBO** [RotherOSS/otobo#1210]
Hi, 

after migration to a docker system the following values are missing in Kernel/Config.pm.
So we have a Cache Problem, cause the Cache changes to FS during migration I think.

114     # ---------------------------------------------------- #
115     # setting for running OTOBO under Docker, see the POD  #
116     # ---------------------------------------------------- #
117     $Self->{'LogModule'}                   = 'Kernel::System::Log::File';
118     $Self->{'LogModule::LogFile'}          = '/opt/otobo/var/log/otobo.log';
119     $Self->{'Cache::Module'}               = 'Kernel::System::Cache::Redis';
120     $Self->{'Cache::Redis'}->{'RedisFast'} = 1;
121     $Self->{'Cache::Redis'}->{'Server'}    = 'redis:6379';
122     $Self->{'Cache::Redis'}->{'Server'}    = 'redis:6379';
123     $Self->{'TestHTTPHostname'}            = 'web:5000';
124
125     # activate Selenium tests if the the host is available
126     $Self->{'SeleniumTestsConfig'} = {
127         remote_server_addr  => 'selenium-chrome',
128         check_server_addr   => 1,                 # skip test when remote_server_addr can't be resolved via DNS
129         port                => '4444',
130         browser_name        => 'chrome',
131         platform            => 'ANY',
132     };

Thanks,

Stefan

**Comment by bschmalhofer** [comment]
Transferred this from the otobo-docker repository, at this seems to concern the migration from OTRS 6  to OTOBO 10.

**Comment by bschmalhofer** [comment]
This is all fairly messy, so let's try to break it up into parts. 

There are two important reasons for having the file _Kernel/Config.pm_. 
1. Provide some kind of bootstrapping for the most basic setting, like the installation directory and the database connection.
2. Provide an opportunity for users to provide configuration in a text file. An example would the CustomerUserMap.

Because of 2. it makes sense to reuse the _Kernel/Config.pm_ from the source OTRS installation. 

Then there is the bootstrapping configuration, which consists of the following settings: 

- DatabaseHost 
- Database 
- DatabaseUser 
- DatabasePw 
- DatabaseDSN 
- Home

These settings are always taken from _Kernel/Config.pm, as they are not saved into the database. The values must come from the target installation, as the database and the installation directory usually changes. This is already handled in the the migration step _OTOBOCopyFilesFromOTRS.pm_ . Albeit, this is not fool proof, as it does depend on formatting conventions in the source file.

So far, so good. But in the docker case the file _Kernel/Config.pm_ is also used for overriding default settings from the _Kernel/Config/Files/XML/*.xml_ files. E.g. die default logging backend is SysLog, which is not useful when running under Docker. This approach is convenient during installation. The downside is that the settings in _Kernel/Config.pm_ override the setting in the SysConfig, and thus the SysConfig can't be used for changing these settings.

So, let's go with the most simple strategy. Inject the missing configuration after the line that sets Home.

**Comment by bschmalhofer** [comment]
Added the missing settings. Did a testmigration and checked _Kernel/Config.pm_. In the migrated installation the value for Cache::Module is now Kernel::System::Cache::Redis. PR is merged.

Looks fine, closing this issue.
