### ISSUE TITLE
Wrong LogModule::LogFile path after migration from OTRS

### ISSUE THREAD

**Issue by OrionExplorer** [RotherOSS/otobo#1297]
Hello,

after a successful migration (OTRS 6.0.30 to OTOBO 10.0.12) I found that custom path provided in Config.pm file was incorrect.

Before migration (in `/opt/otrs/Kernel/Config.pm`):
```
$Self->{'LogModule::LogFile'} = '/opt/otrs/var/log/otrs.log';
```
After migration (in `/opt/otobo/Kernel/Config.pm`):
```
$Self->{'LogModule::LogFile'} = '/opt/otobo/Kernel/Config.pm/var/log/otrs.log';
```

**Comment by bschmalhofer** [comment]
Hi Marcin,
this most likely comes from a but in _Kernel/System/MigrateFromOTRS/OTOBOCopyFilesFromOTRS.pm_ . Specifically the line

> $ChangedLine =~ s/$Param{Home}/$ConfigFile/;

looks dubious. It's a bit strange that this hasn't been noticed before. I suppose that the path _/opt/otrs_ is usually only used for the setting Home. And this setting is reverted to a sane value later in the module.

I'll try to fix this for OTOBO 10.0.13.

**Comment by bschmalhofer** [comment]
Hi @Marcin,

this was actually a combination of two errors. First _/opt/otrs_ was replaced by _/opt/otobo_. Then there was an incorrect replacement that turned the filename into the nonsense name _/opt/otobo/Kernel/Config.pm/var/log/otrs.log_ ,

It is not really trivial what should be replace in Kernel/Config.pm . My take is that the settings added by the user should be left alone, because the migration can't really know what the intention of the setting was. Therefore I added an exeption for the file _Config.pm_. The following replacements are no longer done for _Config.pm_:

> Search            => 'otrs-web',
> Change            => 'otobo-web'
> 
> Search            => '(?<!(Copyright \(\S\) \d\d\d\d-\d\d\d\d ))OTRS',
> Change            => 'OTOBO',
> 
> Search            => '(?<!(Copyright \(\S\) \d\d\d\d-\d\d\d\d OTRS AG, https:\/\/))otrs',
> Change            => 'otobo'
> 
> Search            => '(?<!(Copyright \(\S\) \d\d\d\d-\d\d\d\d OTRS AG, https:\/\/))"otrs"',
> Change            => '"otobo"'

Of course this approach can lead to unwanted results, where _/opt/otrs_ should have been replaced by _/opt/otobo_.

**Comment by bschmalhofer** [comment]
On the other hand, replacing _/opt/otrs_ with _/opt/otobo_ does make sense in many instances. Therefore I enabled that specific rewrite rule.
A testmigration looked good, thus closing this issue.

@OrionExplorer : Thanks a lot for reporting this issue.

**Comment by OrionExplorer** [comment]
@bschmalhofer Thank you!
