### ISSUE TITLE
Two "AgentTicketSearch" in Action=AdminDynamicFieldScreen;Subaction=Edit

### ISSUE THREAD

**Issue by StefanAbel-OTOBO** [RotherOSS/otobo#1335]
In Dynamic Field <-> Screens, when assigning a DynamicField to the different screens, you can see the action AgentTicketSearch twice, instead of only once:
![image](https://user-images.githubusercontent.com/87359203/137931933-f223041d-cc89-4ef0-a8aa-72efd80d898c.png)

In the screenshot, the filter was only used for having a better overview.

Tested in OTOBO 10.0.13 (ov48)

**Comment by reneeb** [comment]
Maybe show a hint when the element is not for a "###DynamicField" setting. One _AgentTicketSearch_ is for the ###DynamicField setting, the other one for the ###DefaultColumns setting:

![grafik](https://user-images.githubusercontent.com/144096/148546739-baa1c8d9-2fff-4ece-b5ea-54a69c7f9fdc.png)

**Comment by svenoe** [comment]
As Renee said, this is for different functionalities. Maybe this can be solved by just changing the sysconfig values and adding an explanation there, I don't know whether they are really used for anything. It cannot be done in the frontend though, because because of the syntax of the keys, the sysconfig breaks when changing those options (see https://github.com/RotherOSS/otobo/issues/991).

When changing those options, we should also add the follow-up dynamic fields for CustomerTicketZoom, I guess. (Currently CustomerTicketZoom only changes which fields are shown in the info.)

**Comment by stefanhaerter** [comment]
Moving this to the wishlist as #2394 is also on the wishlist.
