### ISSUE TITLE
Missleading Daemon Message with Docker Installation

### ISSUE THREAD

**Issue by br-edward** [RotherOSS/otobo#1369]
Hello,

the docker container "otobo_daemon_1" has the state "up", i still receive a message about its need to be run:

![Admin - OTOBO__ITSM 10](https://user-images.githubusercontent.com/87302944/139449239-225c4f61-13ef-4bf5-8d36-32fda82032ee.png)

Thanks for you time

**Comment by bschmalhofer** [comment]
Hello @br-edward,

I checked the source for how `Kernel::Output::HTML::Notification::DaemonCheck` determines whether the Daemon is running. The check is done via the Redis cache. Could you check whether Redis is running in your installation?

Best regards,
   Bernhard

**Comment by br-edward** [comment]
Thank you for you reply @bschmalhofer 

Redis is not installed, will the Daemon not work without Redis?

Thank you very much

**Comment by bschmalhofer** [comment]
Ah, that is the first step in explaining the effect.

First, the Daemon can also run with the File based cache. But I see other problems. Not that the following paragraphs are to be taken with a grain of salt, as I don't know your setup.
 
When a process is running under Docker, then the default setting is that each process has its own file system. But in the case of OTOBO, there are some advantages when the OTOBO web server and daemon have a shared file system. That's why in the default Docker compose configuration, https://github.com/RotherOSS/otobo-docker, the directory _/opt/otobo_ is a persistent volume that is shared between web server and host. Running without Redis, there would be shared file based cache that can be abused as a means of communication between daemon and webserver.  The same logic applies when both web server and daemon use the same instance of Redis.

But you setup seem to run without a shared _/opt/otobo_ . Did you simply start Daemon and web server as separate Docker processes? This would be an use case that needs special consideration. The misleading message is then just the most harmless manifestation of things that can go wrong in that setup. See the discussion in https://github.com/RotherOSS/otobo/discussions/1148.

My advice is that you start with OTOBO running with a shared _/opt/otobo_. This can be done in several ways. First you can tweak the standard OTOBO Docker Compose setup to your needs. Or you can the OTOBO Docker images directly with Docker, but in this case you would have to set up the shared volume _/opt/otobo_ yourself. In the latter case also take a look at _/opt/otobo_install/entrypoint.sh_ .  In that script there are function that set up /opt/otobo.

**Comment by br-edward** [comment]
> But you setup seem to run without a shared _/opt/otobo_ . Did you simply start Daemon and web server as separate Docker processes? This would be an use case that needs special consideration. The misleading message is then just the most harmless manifestation of things that can go wrong in that setup. 

I followed this guide: https://doc.otobo.org/manual/installation/stable/en/content/installation-docker.html#clone-the-otobo-docker-repo but that should have installed the Redis Container, automatically probably. I moved away from Docker and use the manual Install now. So I cannot confirm no Redis was running as otobo_redis_1.

**Comment by bschmalhofer** [comment]
Ah, thanks for clarifying that. I was wandering off into a different direction. So it does look like there was a communication problem between the running daemon and the GUI. The most simple explanation would be that Redis was either not running or had other undetermined problems.
Closing this issue as it looks like a special case.
