### ISSUE TITLE
AgentCustomerSearch in new ticket dialog not showing customer users with same name

### ISSUE THREAD

**Issue by wornet-aer** [RotherOSS/otobo#1421]
Unfortunately I live in a world, where the same external consultant works for multiple customer companies.

So, I have two customer users:
```
login: 111.maxmuster
customer_id: 111
first_name: Max
last_name: Muster
email: max.muster@example.org
```

```
login: 222.maxmuster
customer_id: 222
first_name: Max
last_name: Muster
email: max.muster@example.org
```

When composing a new email or phone ticket and typing 'Muster' into the customer user field, I only get one suggestion for `"Max Muster" <max.muster@example.org> (111.maxmuster)` and none for his user account at the other customer company.

However, when using the address book icon (at the end of the input field) to search for this user, I get the two expected results.

So I assume, that the `AgentCustomerSearch` can't handle user accounts with the same name and email, whereas `AgentCustomerUserAddressBook` correctly returns all occurrances.

I am aware that this scenario is a quite akward and difficult situation, because incoming tickets will be always assigned to the first user account with the specific sender email address. But I think, when actively composing new tickets by an agent, it should be possible to select the right user account/customer anyway.

Maybe someone can give me a quick hint, where to fix this behaviour. 
I can try to prepare a PR then. :)

**Comment by StefanAbel-OTOBO** [comment]
Hello,

therefore you can assign one customer user to multiple Customer IDs and then assign a ticket to a different Customer ID.

Best regareds

**Comment by wornet-aer** [comment]
Unfortunately it seems impossible to assign one customer user to multiple customer companies. I can only select one customer company when editing the customer user.

Did I miss something?

**Comment by svenoe** [comment]
Hi Andreas,

actually I had to look into the code for this, as it didn't come up for to long. In the admin interface there still is a "CustomerUsers <-> Customers" relations section. We disabled the customer selection for the standard, as it rarely is needed, but if you uncheck Ticket::Frontend::AgentTicketPhone::CustomerIDReadOnly, you should be able to switch between the main and the secondary CustomerIDs in AgentTicketPhone e.g.. Please have a look at this and see if it helps you.

On a sidenote - we try to keep github free of support issues, for that we ask people to go to our [forums](https://otobo.de/en/forums/otobo/otobo-forum/), because then the community can often help, too. I know that in this case you thought it was a development issue (and likely no one could have answered there, actually), so it's ok. I just write it for your awareness and I will close the issue for now at least, that it is out of the mind of others. Please do write some feedback, here, on whether the stuff I wrote before works for you, anyways! ;)

Have a nice week, Sven

**Comment by wornet-aer** [comment]
Hi Sven,

thanks for your quick response and the good hint!
As you pointed out, I'm aware of the forums and thought about a development issue in this case.
For me this issue can be seen as solved now.

However, I'm still not sure, if the behaviour of the customer user search field is correct in this case. From my perspective it should list all customer users with the given name or address and not just the first one.

Cheers, Andreas

**Comment by svenoe** [comment]
Actually I agree, I was more focused on the later stuff, with Stefans response. A standard system however doesn't even give you the opportunity to create two customer users with the same email address (of course I'm aware that with external DBs or LDAP or so, this is easily possible anyways). Just as a last quick test, you could check what you are using as CustomerKey in your CustomerUser definition in the Config.pm (if you have it set there). If it's "email", then maybe this is the reason...

**Comment by wornet-aer** [comment]
The setting `Customer::AuthModule::DB::CustomerKey` has the value `login` in my case. IMHO this should be correct, as the logins contain the customer number and are unique, even if name and email aren't.
