### ISSUE TITLE
It is impossible to find out the field names if they are too long.

### ISSUE THREAD

**Issue by RGronau** [RotherOSS/otobo#1474]
Hello all

Even hovering over it does not show the name. It is therefore impossible to find out which fields have already been entered! Once there are 20, 30, 100, 200 fields in there. What do you do then? You would have to use an external Excel list to remember which fields are in which row.

A workaround solution would be simple.
Change the ratio of field names to values to 50:50.

A better solution would be to generally allow reading in the left field name field including scrolling.

And the best solution would be that these entries could also be inserted into the GUI 'Dynamic fields <-> surfaces'.

![image](https://user-images.githubusercontent.com/95427123/144563526-8a89eff6-5ab0-40f4-b3b7-007f960eac58.png)

**Comment by svenoe** [comment]
Hi RGronau,

I see your point, without having tested it, you could quite likely use the import-export functionality for the SysConfig, though. Also care would have to be taken when changing the size, because in other cases, where you have nested structures a plain 1:1 ratio is also not, what you want. I will add this to the list of possible enhancements and close the issue for now. I don't see this having a high priority, though.

Best regards, Sven

**Comment by stefanhaerter** [comment]
Just for information:

> And the best solution would be that these entries could also be inserted into the GUI 'Dynamic fields <-> surfaces'.

Has been done in #4355 for rel-11_1.
