### ISSUE TITLE
CustomerCompanySearchListLimit and CustomerUserSearchListLimit do not work in the overview pages

### ISSUE THREAD

**Issue by StefanRother-OTOBO** [RotherOSS/otobo#1539]
CustomerCompanySearchListLimit and CustomerUserSearchListLimit do not work in the overview pages. Until now, a limit of 400 always applied here, unless Customer*SearchListLimit was smaller than 400. From now on, the value stored in the configuration also applies to the AdminCustomerUser and AdminCustomerCompany overview pages.

**Comment by svenoe** [comment]
This should be changed. The `$Limit` here is really only used to check whether more results would be available without limit. This was not programmed really precise, but the current changes just improve a very specific case, which is one Customer backend with a large limit. Actually for the code to really work the largest limit + 1 would have to be chosen (which is impossible if no limit is defined in the map at all, where it falls back to a hardcoded 250 for Kernel/System/CustomerUser/DB.pm, to 50000 for Kernel/System/CustomerCompany/DB.pm,...), instead of the smallest + 1 and then the size of both results would have to be compared instead of a comparison to the `$Limit`, but we shouldn't do that for possible performance issues. Thus in my opinion we should keep it as it is and just use the hardcoded values (changed to 250 and 50000, matching their DB counterparts), if no limits are defined in any map. Thus the problem will be solved for single backends, and multiple backends might have a "more are available" erroneously shown for different limit sizes of different backends, where the smallest limit still is larger than its content, but is restricting the other backends.
