### ISSUE TITLE
Allow change of Customer Dashboard welcome text and TitleTicketList in SysConfig

### ISSUE THREAD

**Issue by GritRother-OTOBO** [RotherOSS/otobo#1627]
For languages differentiating a formal and informal way of address (German: Du/Sie) it would be great if 

- the Welcome text for the dashboard header (CustomerDashboard::Configuration::Text) and
- the subtitle for the ticket list on the dashboard "Your tickets"  (Kernel::Output::HTML::CustomerDashboard::TileTicketList)

would be editable in the SysConfig.

**Comment by svenoe** [comment]
The problem here are ticket systems which customers speaking different languages will use. Configurable SysConfig values are usually not translated (especially free texts). We could introduce an exception here, of course, but we again have a problem then, if one wants to use the English "Your tickets" and the German "Deine Tickets", and another one wants to have "Your tickets" translated(!) to "Ihre Tickets".

In my opinion the real solution here would be to provide a nice way for the OTOBO admin to maintain a custom set of translations, without having to edit perl modules. This is something which would be great for many other places...
