### ISSUE TITLE
Searching in Dynamic Field of type Database triggers Redis Error

### ISSUE THREAD

**Issue by stefanhaerter** [RotherOSS/otobo#1691]
Using a docker installation of otobo 10.1 with .env file for Selenium tests, autocomplete in Dynamic Field Database triggers the following error:

[Error][Kernel::System::Cache::Redis::Set][86] ???

The Dynamic Field Configuration is the following:

![Bildschirmfoto_2022-03-28_10-12-02](https://user-images.githubusercontent.com/46650328/160354744-89b76036-f543-4ca3-9d86-bcb1b58ffc5d.png)

**Comment by bschmalhofer** [comment]
The error message comes from Redis, or Redis::Fast, because TTL = 0 is no acceptable time to live. As setting the TTL to zero effectively disables caching, there is no need to set the cache in the first place. Thus the error message can be avoided.

More interesting is why the message '???' is added to the log output. This seems to be a side effect of the following code:

```
    if ($@) {

        $Kernel::OM->Get('Kernel::System::Log')->Log(
            Priority => 'error',
            Message  => $@,
        );

        return;
    }

```
`$Kernel::OM->Get('Kernel::System::Log')`resets $@ before $@ is passed as the message. This behaviour can be reproduced with this example:

```
use v5.24;

eval {
    die "Achtung Ausnahme";
};

if ( $@ ) {
    Log->new()->Log($@);
}

package Log;

sub new {
    my ($Class) = @_;

    # effectively: undef $@;
    eval {
        #die 'die in new';
        my $x = 'u';
    };

    return bless {}, $Class;
}

sub Log {
    my ($Self, $Message) = @_;

    say "Log '$@'";
}

```

The fix is to make a copy of `$@` before logging.

**Comment by bschmalhofer** [comment]
This has been handled by checking for `$CacheTTL`.
