### ISSUE TITLE
No Docu about   Ticket::CustomerViewableStateType?

### ISSUE THREAD

**Issue by superwinni2** [RotherOSS/otobo#1721]
Hello

I want that Customers can take a Look with the Webbrowser if they click at "Tickets" in customer.pl Frontend.
If they click on "Tickets" I get the message in log:
Apr 14 14:07:53 OTOBO OTOBO-CGI-00[44248]: [Error][Kernel::System::State::StateGetStatesByType][Line:378]: Type 'Ticket::CustomerViewableStateType' not found in Kernel/Config.pm!

I'm looking for the Options of "Ticket::CustomerViewableStateType" which were implemented in 10.1?
Anybody know what I need to configure? I can't find any documentation about?!?

Thanks and Greetings

**Comment by bschmalhofer** [comment]
Hi @superwinni2 ,

the configuration setting Ticket::CustomerViewableStateType was added for OTOBO 10.1.1. See https://github.com/RotherOSS/otobo/issues/1543. The setting is declared in _Kernel/Config/Files/XML/Ticket.xml_. In order to be usable in OTOBO this new setting must be merged into the actual system configuration. This is done with the command `/opt/otobo/bin/otobo.Console.pl Maint::Config::Rebuild` .  In my opinion no special documentation is needed for this case. The required command is already documented in https://doc.otobo.org/manual/installation/10.1/en/content/updating.html#step-5-update-installed-packages-and-reconfigure-config .

Closing this issue for now. Please reopen if this does not work for you.

Best regards,
    Bernhard
