### ISSUE TITLE
Update JavaScript libraries

### ISSUE THREAD

**Issue by bschmalhofer** [RotherOSS/otobo#1722]
Bring the JS libraries to their current versions. Be inspired by https://github.com/znuny/Znuny/blob/rel-6_3_1/CHANGES.md.

- jQuery
  - upgrade JQuery to 3.6.0
  - keep the _.min_ in the name _jquery-3.6.0/jquery.min.js_
- remove jquery-migrate-3.0.0 as it was unused and not up to date
- jquery-ui
  - generate a custom download with the feature list from https://github.com/OTRS/otrs/commit/05dbcf42415d3db54822486128f9169baea0f450
  - Note that Znuny has expanded the feature list for no apparent reason
  - Also update jquery-ui.min.css, apparently the CSS hasn't been updated since 2014
  - jquery-ui.min.css already includes jquery-ui.structure.min.css and jquery-ui.theme.min.css  See https://jqueryui.com/upgrade-guide/1.11/#simplified-custom-and-quick-downloads
  - update the icons in skins/Customer/default/css/thirdparty/ui-theme/images/
  - update the icons in skins/Agents/default/css/thirdparty/ui-theme/images/
  - remove the images that were no longer included in the custom download

**Comment by bschmalhofer** [comment]
The current version of CKEditor 4 is 4.18. But upgrading CKEditor should be handled in #790.

**Comment by bschmalhofer** [comment]
Looks like _jquery-browser-detection.js_ can't be removed as the method `browser` is used in _./var/httpd/htdocs/js/Core.App.js_ .

**Comment by bschmalhofer** [comment]
Also update qunit to version 2.18.2

But as of 2024-06-27  qunit is now at 2.21.0

**Comment by bschmalhofer** [comment]
The test suite ran fine. PR is merged. Let's keep this issue open, checking whether problems crop up.

**Comment by bschmalhofer** [comment]
Two more updates as seen in https://github.com/znuny/Znuny/tree/rel-6_3-dev/var/httpd/htdocs/js/thirdparty:
- momentjs-2.29.1   (actually using 2.29.3)
- nunjucks-3.2.2

**Comment by stefanhaerter** [comment]
I updated the jquery-ui from 1.12.1 to 1.13.2. First, I adjusted the paths. Afterwards, I committed the js and css files. 

The jquery-ui homepage appears to offer different themes. An error in customer user selection seemed to occur from a wrong theme. As far as I could manage to find out, the right one is **Smotheness**.

Site note: Currently (or at least in my browser) the select element on the jqueryui page appears to be broken so that the selected theme is not downloaded. I had to add the select to the option in the inspector. In every jquery-ui.min.css is a link to view the theme in browser, so it is easy to verify the theme.

**Comment by stefanhaerter** [comment]
Merged.

**Comment by stefanhaerter** [comment]
Another site note: It is important to check the minified css as well as the minified js for the selected modules. So far, the following list is to be included for Otobo:

- Widget
- Position
- :data Selector
- disableSelection
- :focusable Selector
- Keycode
- scrollParent
- :tabbable Selector
- uniqueId
- Draggable
- Droppable
- Resizable
- Sortable
- Autocomplete
- Datepicker
- Menu
- Mouse
