### ISSUE TITLE
Maybe bug based on #1741LDAP Auth / Roles

### ISSUE THREAD

**Issue by manuelveith** [RotherOSS/otobo#1753]
I was upgrading from 10_0_3 to 10_1_4 and may have encountered a problem with a bug that was solved with #1741

I use LDAP Auth but don't use AD groups to bind the roles to the agents. I bind the roles in Otobo. 

After the update everytime when an Agent logs off and on again, his roles are all gone. I can reassign them, but after logging in they are gone again. 
Is it possible that the fix deletes manually assigned roles from LDAP Users because I don't use LDAP groups to assign roles?

**Comment by svenoe** [comment]
Hi Manuel,

could you please download the newest version of [Kernel/System/Auth/Sync/LDAP.pm](https://github.com/RotherOSS/otobo/blob/rel-10_1/Kernel/System/Auth/Sync/LDAP.pm) (right click on "Raw", and "save target as"), make a backup of your old one and then replace the file? I hope this will solve the problem. The initial "fix" of https://github.com/RotherOSS/otobo/issues/1608 was not done correctly and that led to quite some confusion later, sorry about that...

Best regards, Sven

**Comment by manuelveith** [comment]
Hi Sven,

I corrected my post that it is related to #1741 not #1608. So the latest version is already in 10.1.4 I would say. 
What I can say is, I reverted my upgrade and then upgraded with release 10.1.3 and the problems did not occure there.

**Comment by svenoe** [comment]
Hi Manuel,

yes, I understood. #1608 and #1741 are related. With your setup 10.1.3 can be used. It is buggy for people using one type of role synchronisation. The latter got fixed with 10.1.4 but this broke your setup. As I said, there was some confusion, unfortunately. By now I correctly fixed the file, so an alternative would have been to use the one linked above.

I will close this issue, as you don't have problems with 10.1.3 anymore. 10.1.5 will be usable for you, again.

Best regards
