### ISSUE TITLE
Values in ticket information and customer information widget is lower than labels

### ISSUE THREAD

**Issue by StefanAbel-OTOBO** [RotherOSS/otobo#1774]
When you compare in AgentTicketZoom in the Widgets "Ticket information" and "Customer information", you can see that a slight height difference is there compared between the labels and their values.

![Bildschirmfoto 2022-05-12 um 13 48 49](https://user-images.githubusercontent.com/87359203/168116312-c53f5819-9ec2-487c-9cd5-5f754fdad128.png)
<img width="424" alt="Bildschirmfoto 2022-05-12 um 13 49 06" src="https://user-images.githubusercontent.com/87359203/168116401-e9608d41-f7b6-40a3-ac50-6e5ccdadc121.png">

**Comment by stefanhaerter** [comment]
This is due to different margins for labels and class Value within fieldset tables. I investigated this and it occurs that the relevant code stems from OTRS. I will make a PR, since this does not only affect the ticket information widget, but also (but not necessarily limited to):

- AgentStatisticsReportsView
- AdminPackageManager
- GeneralSpecificationWidget
- StatsParamsWidget

I would change the padding of the Value class because this is less invasive (labels are not only used with static Value elements, but also with Field elements).
