### ISSUE TITLE
Have a look at style options for images in the CKEditor.

### ISSUE THREAD

**Issue by svenoe** [RotherOSS/otobo#1882]
CKEditor allows for image styling (setting width, height, alignment). In instances which do not support picture upload (e.g. Admin->Signatures) those styles are deleted upon saving (or turning on and off the source mode). As you can still embed pictures using the source mode and adding `<img src='https://link/to/picture.png'>` or pasting base64 encoded pictures, this behaviour is definitely not wanted.

A location to start investigating this would be: https://github.com/RotherOSS/otobo/blob/f69a6b4bee26b419e5db8f57596a55fd8fd62c30/var/httpd/htdocs/js/Core.UI.RichTextEditor.js#L175-L187

Here, I believe the extraAllowedContent should be usable to allow this, but maybe (also) image2 cannot be removed via removePlugins, I'm not certain. I would believe this is the right place in any case.

**Comment by stefanhaerter** [comment]
extraAllowedContent is apparently the right place to look at, and my current research shows that there is a very simple solution: Extent `img[*]` to `img[*]{*}`.

I will now explain how this works:
The default setting for allowedContent is to apply the Advanced Content Filter according to definitions in the editor config and the toolbar. So, the toolbar e.g. in Admin->Signatures does not have the Image button. In extraAllowedContent, the img tag is defined as follows:
`img[*]`
The [documentation for filter configuration](https://ckeditor.com/docs/ckeditor4/latest/guide/dev_allowed_content_rules.html#string-format) says the syntax for (extra)allowedContent is as follows:
`elements [attributes]{styles}(classes)`
So, the style tags disappear because they are indeed currently not allowed.

_Side learning: The toolbar configuration seems to overwrite this special setting, if the Image button is present._

For now I think the fix is fine, but maybe it is worth a discussion which attributes, styles and classes should be allowed regarding the [security best practices given](https://ckeditor.com/docs/ckeditor4/latest/guide/dev_best_practices.html#use-acf-in-default-automatic-mode).

**Comment by stefanhaerter** [comment]
Closing this as complete.
