### ISSUE TITLE
Sender display name not always quoted

### ISSUE THREAD

**Issue by abrain** [RotherOSS/otobo#1953]
We had delivery issues with some of our OTOBO emails when sending to GMX or web.de.

After some testing we found that the problem was that some of the display names of our system addresses contain square brackets, e.g. `[foo] bar`. At first, we discarded this possibility because auto-replies containing those display names were delivered just fine.

But checking the unformatted messages we found the following difference:
- Auto reply: `From: "[foo] bar" <foo@example.org>`
- Outgoing mail: `From: [foo] bar <foo@example.org>`

The display name does not get quoted for outgoing mail.

Reading through RFC 2822 I think it does not hurt to always quote the display name. From what I understand it would already be necessary as soon as the display name contained a space (ASCII 0x20).

**Comment by bschmalhofer** [comment]
Hi Andreas,

intuitively I would agree that different From-Headers in different situations are a bug anyways. With square brackets in the display name quotes would be needed. As a side note, I think that `From: foo bar <foo@example.org>` would be valid as a list of words is allowed.
I will look into this, but it might take some time.

Best regards,
    Bernhard

**Comment by bschmalhofer** [comment]
I can confirm the effect on my local test installation. The Auto Reply quotes the display name when there are square brackets. AgentTicketPhone does not.

**Comment by bschmalhofer** [comment]
Inspecting the code, the differing behaviour is comprehensible. When sending auto responses, the From address is formatted with `Mail::Address::format()`. See https://github.com/RotherOSS/otobo/blob/rel-10_1/Kernel/System/Ticket/Article/Backend/Email.pm#L660 and https://github.com/OTRS/otrs/commit/696fcb12d3d267890b6142c1b62b9ce1a0a94268.

The same fix should be applied to `Kernel::System::TemplateGenerator::Sender()`. See https://github.com/RotherOSS/otobo/blob/rel-10_1/Kernel/System/TemplateGenerator.pm#L355 .

More specifically, the regex in TemplateGenerator `/([.]|,|@|\(|\)|:)/` is not correct and has an unnecessary capture, The correct regex, as used in `Mail::Address` is `my $atext = '[\-\w !#$%&\'*+/=?^`{|}~]';  /^(?:\s*$atext\s*)+$/` . Where `Mail::Address` checks for while listed characters instead of an incomplete blacklist.

Let's fix this only for the 10.1 branch, as this effect apparently occurs only very rarely.

**Comment by bschmalhofer** [comment]
PR is merged, closing this issue.
