### ISSUE TITLE
Appointment notifications are not sent when IsVisibleForCustomer is set

### ISSUE THREAD

**Issue by bschmalhofer** [RotherOSS/otobo#1954]
In the appointment notification admin frontend on can check the "Article visible for customer" checkbox. 
![Bildschirmfoto vom 2022-09-24 16-09-44](https://user-images.githubusercontent.com/46019/192102686-fa4bd661-ca25-49bf-9624-31a077be0918.png)

But when the checkbox is set, then no appointment notifications are sent out. 
The reason is that there is a blacklist for appointment attributes that are not checked by the filter. And the attribute IsVisibleForCustomer is missing there. See https://github.com/RotherOSS/otobo/blob/rel-10_1/Kernel/System/Calendar/Event/Notification.pm#L315 .

It should also be investigated what IsVisibleForCustomer actually does.

**Comment by bschmalhofer** [comment]
A scant look into the code did not show a significant use of IsVisibleForCustomer. It could be used in a notification templete. But apparently no article is created. So there is no use case where an article would be marked as visible for customers.

**Comment by stefanhaerter** [comment]
While investigating another issue, I found that this is due to or at least influenced by sub _NotificationFilter in Kernel/System/Calendar/Event/Notification.pm. The key 'IsVisibleForCustomer' is not skipped unlike many other ones, so the evaluation goes here:
https://github.com/RotherOSS/otobo/blob/b1fac505151f4606690cdcbfae07f4cf316e0645/Kernel/System/Calendar/Event/Notification.pm#L382
And because 'IsVisibleForCustomer' is not defined in the Appointment data (at least in my testing example), the evaluation fails.

(At the moment, I don't know what would be a proper way to fix this. We could add IsVisibleForCustomer to the skipped keys, but I have no clue what the purpose of skipping the keys is)

**Comment by bschmalhofer** [comment]
When this situation occurs, than a quick workaround is to uncheck "Article visible for customer". Still not sure whether this has any side effects.

**Comment by bschmalhofer** [comment]
PR is merged in rel-10_0 and rel-10_1. @stefanhaerter could you do a quick test?

**Comment by stefanhaerter** [comment]
Fix works for 10.0 and 10.1, closing this issue.
