### ISSUE TITLE
migration.pl correct setting for Package::RepositoryRoot

### ISSUE THREAD

**Issue by ghost** [RotherOSS/otobo#1976]
The Migration script (from Znuny LTS to OTOBO) has updated everything correct, excluded Package::RepositoryRoot. Please check if the Migration Script is currently updating this value.

**Comment by bschmalhofer** [comment]
Hi Markus,
thanks for reporting this. This effect has been encountered before. See e.g. https://otobo.de/de/forums/topic/unable-to-update-packages-using-package-manager-error-404/.
The fix should be simple. When migrating the value of `Package::RepositoryRoot` must be reset to the default value. I'll provide the fix for OTOBO 10.1.6,

**Comment by bschmalhofer** [comment]
Hi Markus,
I have added `Package::RepositoryRoot` to the list of setting that are to be reset, see https://github.com/RotherOSS/otobo/blob/bd45243c936364df7ebae0e6867b5549a19caf55/Kernel/System/MigrateFromOTRS/Base.pm , Could you redo your migration with the changed file _Kernel/System/MigrateFromOTRS/Base.pm_ and check whether the repositories now appear on the package admin page?

Best regards,
   Bernhard
