### ISSUE TITLE
Frontend::Module###AgentTicketFreeText and Ticket::Frontend::MenuModule###310-FreeText wrong title

### ISSUE THREAD

**Issue by ghost** [RotherOSS/otobo#1978]
Wrong Title: Change Ticket
Correct Title: Change Ticket information

Because of the missing word "information" the String is not translated correct. In the de.pm are 2 translations ("Change ticket" seems only for ticket categorization):
'Change Ticket' => 'Ticket kategorisieren',
'Change Ticket information' => 'Ticketinformationen ändern',

**Comment by stefanhaerter** [comment]
Hi Marcus,

I assume that the two different translations are intended because 'Change Ticket' is used as displayed text and 'Change Ticket information' is set as title which appears when you hover over 'Change Ticket'. This behavior is consistent across (at least) German and English (US) language setting. As far as there are no indications for an error, I would suppose that this is correct.

Kind regards,
Stefan

**Comment by stefanhaerter** [comment]
Closing this.
