### ISSUE TITLE
Postmasterfilter matching errors for regexes including $.

### ISSUE THREAD

**Issue by svenoe** [RotherOSS/otobo#2063]
Please ask @KhalilHamada-OTOBO for more info.

**Comment by stefanhaerter** [comment]
It appears to be the case that some regex-relevant characters get escaped. `\` are already escaped when retrieving them via `$('...').val()` in Javascript. `$` are sent non-escaped in the form submit but are escaped in `$Param` in the module. `^` seems to be not affected by this. 

I would suggest to do a bit of parsing to the regex in `Kernel/System/PostMaster/Filter/MatchDBSource.pm` here:
https://github.com/RotherOSS/otobo/blob/e35e90133c12f120491e0bf14501ab60a1ac1e5f/Kernel/System/PostMaster/Filter/MatchDBSource.pm#L94-L96

Since we can assume that every normal `\` arrives as `\`, we can remove one at each occasion. Since `$` is the only other sign we currently know that it is affected, I would also remove `\` in front of `$` if there is exactly one (in opposition to `\\$`, which is intended to be an escaped `$`).

**Comment by stefanhaerter** [comment]
Tests showed that regex matching seems to be working technically correct. An important difference is the following:

- /Regex/ matches against: 'John Doe <john.doe@test.com>'
- /EMAILADDRESS:Regex/ matches against: 'john.doe@test.com'

The documentation in the side bar in AdminPostmasterFilter is correct. I would opt for including an example with EMAILADDRESS at [doc.otobo.org](https://doc.otobo.org).

Also, the logging behavior should be adjusted. In case /Regex/, the filter includes a line in the message protocol also when it did not match - it doesn't do so in case /EMAILADDRESS:Regex/. As long as this isn't supposed to be or intended, I would opt for aligning the behavior.

**Comment by svenoe** [comment]
In the end we could not reproduce it. Waiting for a case where it shows up again.
