### ISSUE TITLE
Agent roles still not appliying

### ISSUE THREAD

**Issue by MikeW83** [RotherOSS/otobo#2126]
The Issue https://github.com/RotherOSS/otobo/issues/2114 has been resolved too early. I have still one user where all roles get cleared at logon even if the logging says that the roles has been assigned.

**Comment by MikeW83** [comment]
Hello. Please don't close it. I still have a user where the roles are cleared when logging in.

**Comment by svenoe** [comment]
See my answer in #2114 - I can reopen the other issue if need be.

**Comment by MikeW83** [comment]
I understand and I'm the last one who doesn't understand which passion is behind an open source project. I cannot figure out what is happening. There is not much logging for this. The debug log says that the roles have been applied. But they aren't. In this case I have to set manually the roles for the user session. And after a new login everything is cleard up.
And this is definitly not normal.

**Comment by svenoe** [comment]
We are having quite some customers which are using role synchronisation, and especially since we had a bug there, which some of them experienced, and is fixed now, I'm quite confident that at least for standard cases there are no issues right now.
For migrations oftentimes mixups between OTRS and OTOBO in role names etc. can cause a lot of confusion (and our migration routine replaces some, but not all instances of OTRS - it's impossible to automate this in a general way for custom settings), so maybe this would be a place to check things.

It's difficult to say anything real without looking at the system though - or alternatively reproduce the error, as written in the other issue...

**Comment by MikeW83** [comment]
I have found a reason why it's not working only for two users. We have multiple backends, but the same samAccountName and that's causing our problem.
Sorry for bothering you

Best regards, Michael
________________________________

**Comment by svenoe** [comment]
Good to hear :)
(And sorry for being a bit reluctant here, but it's just not so efficient if immediately some developers look through the code for potential bugs...I guess you understand. ;)
