### ISSUE TITLE
Textarea font is different in different view

### ISSUE THREAD

**Issue by StefanAbel-OTOBO** [RotherOSS/otobo#2142]
The Dynamic Field "TextArea" has different fonts compared to the DynamicField "Text" in several views. And it even has a different font compared to itself (depending on the View).

The Dynamic Fields "Text" and "TextArea" font in AgentTicketPhone looks like this:
<img width="432" alt="image" src="https://user-images.githubusercontent.com/87359203/214614520-af85bc30-a767-4868-8fea-4fb2b46e9021.png">

The Dynamic Field "Text" and "TextArea" font in a Process Activity Dialog looks like this:
<img width="507" alt="image" src="https://user-images.githubusercontent.com/87359203/214614736-6e83724d-3b40-4ab2-aa04-acd14323c9fb.png">

Especially with the "y" you can see the differences.
The font for "Text" looks consistent in each view. The font for "TextArea" is neither consistent, nor fitting the font of the "Text" field.

**Comment by StefanAbel-OTOBO** [comment]
You can test it on OV139

**Comment by stefanhaerter** [comment]
Having a quick look, this seems to be due to this CSS setting:
https://github.com/RotherOSS/otobo/blob/9a6e290ad2a3137576d9940b16026358d8fd9292/var/httpd/htdocs/skins/Agent/default/css/Core.Agent.TicketProcess.css#L148-L151
I would second the call for consistency, but I'd like to know first if this could be intended for some reason.

**Comment by stefanhaerter** [comment]
Closed with merging #3351
