### ISSUE TITLE
Process name in process selection dropdown is not translated

### ISSUE THREAD

**Issue by StefanAbel-OTOBO** [RotherOSS/otobo#2146]
In Action=AgentTicketProcess in the dropdown the process name is not translated in the dropdown, despite the fact that after selecting a process, the process name is selected in the same action in the process information widget on the right hand side.

![Bildschirm­foto 2023-01-31 um 10 44 53](https://user-images.githubusercontent.com/87359203/215725120-7b760b6c-5de2-40fd-9276-1b514d697eba.png)

I selected the "Bug" label, as this might be quite a big problem depending on the use case and it is not consistent.

**Comment by StefanAbel-OTOBO** [comment]
OV139

**Comment by stefanhaerter** [comment]
The main question here is regarding consistency since the initially required code change is marginal. So I checked how the translation is handled in other places:

__Occasions which perform translation:__

-  AdminProcessManagement [process overview]
- AgentTicketProcess [process information widget]

__Occasions which do not perform translation:__

- AgentTicketProcess [process selection]
- AgentTicketZoom [ticket information widget, process information widget]
- AgentTicketPrint
- CustomerTicketProcess [ticket title, ticket information widget]
- CustomerTicketPrint

Most likely there are occasions left which I didn't think about. However, I would opt for being consistent throughout the whole system and suggest to adapt the non-translating places. @svenoe what is your opinion on this?

**Comment by stefanhaerter** [comment]
Explanatory comment: To be discussed.

**Comment by stefanhaerter** [comment]
Closed with merging #2199
