### ISSUE TITLE
Suggestion: remove the AgentZoom frontend module

### ISSUE THREAD

**Issue by bschmalhofer** [RotherOSS/otobo#226]
As OTOBO is a new system no compatability support is necessary.

**Comment by svenoe** [comment]
We allow migration from otrs, so it would have to be clarified which versions are affected by this:
`#`
`# LEGACY: This module redirects to AgentTicketZoom. It should be kept for a while`
`#   because existing legacy/upgraded systems have it in their notifications.`
`#   To drop it, existing notifications would have to be changed by the database`
`#   upgrading script.`
`#`

And whether it is realistic that older systems will be upgraded that far.

**Comment by svenoe** [comment]
Remove in 11.0. Document this in the developers manual, when it is up.

**Comment by bschmalhofer** [comment]
Move to milestone 10.0, just to have future developments in one place.

**Comment by stefanhaerter** [comment]
I assume this one was overseen for rel-11_0. @svenoe  is this a topic for rel-11_1?

**Comment by bschmalhofer** [comment]
AgentZoom frontend is finally removed for OTOBO 11.1.1. Leaving the issue closed, but assign it to the milestone 11.1.1.
