### ISSUE TITLE
SessionID in old cookies can trap client on the login page.

### ISSUE THREAD

**Issue by svenoe** [RotherOSS/otobo#251]
Probably connected to switching between HttpType https and http. For me in connection with different instances of otobo running under the same ip. Easily solved by removing the cookie from the client browser, but impossible to identify without debugging the code or knowing about it. (Client just is stuck on being redirected to the login screen with the message: 'Session invalid. Please log in again.')

See Kernel/System/Web/InterfaceAgent.pm, where the SessionID from the Cookie overrides others. Probably has to be fixed by removing cookies everytime an invalid SessionID is encountered, just in case.

**Comment by svenoe** [comment]
Can be reproduced by:
1. HttpType => http setzen (z.B. in der SysConfig)
2. Sich im Browser als Agent via http einloggen (Cookie wird angelegt)
3. HttpType => https umstellen (z.B. in der SysConfig)
4. bin/otobo.Console.pl Maint::Session::DeleteAll ;#löscht alle sessions
5. Im browser wieder via http /otobo/index.pl aufrufen und sich anmelden (schlägt dann immer fehl)

**Comment by bschmalhofer** [comment]
@svenoe I tried to reproduce this but never got to the situation where I could not log in. I can think of some difference between your and my environment. Therefore my questions.

- Which browser were you using? I have Firefox 79.0.
- Is OTOBO running on the local machine ?  I only tested with  localhost.
- Could you check the value of 'Secure' on the cookies? 

When HttpType is set to 'https' and I access OTOBO via http I silently get  a cookie with Secure = No. Maybe your browser refuses to accept a cookie with Secure = Yes from a HTTP site.

**Comment by bschmalhofer** [comment]
Hi @svenoe,
 
I have done some more investigation. For that I did a minor cleanup up cookie related stuff in the rel-10_0 branch. The only significant change should be that the  OTOBOBrowserHasCookie should now have the same Expire time as the OTOBO session cookie. In my opinion it is weird to set the time to life of a cookie to one year in the future.

My theory is that the Secure flag of the session cookie is handled differently between your and my setup.  The secure flag of cookies in set in OTOBO  when HttpType is set to the value 'https'. In more detail, the server stores a cookie on the client, and tries to tell the client to mark that cookie as secure. When a cookie is marked as secure on the client, then the client user agent usually sends the cookie only over HTTPS back to the server. The client considers cockies with or without secure flag as different cookies. The problem is when OTOBO is accessed via HTTP. In my setup the secure attribute is somewhere dropped along the line. This means that in my setup the new session cookie is:
- sent from the server to the client, effectively **without** secure flag 
- overwrites the old session cookie at the client
- sent back to the server and and accepted there
- =>I am logged into OTOBO.  

My suspicion is that in your setup the secure flag is not dropped.  This gives following setup:
- the server send the new session cookie to the client, with **secure** flag
- the new session is stored as a second cookie on the client, the old cookie is not overwritten
- as the connection is via HTTP, the old, non-secure, cookie is sent back to the server
- Login is denied and you are stuck on the login page

However my theory has a big flaw. Why does the connection work after deleting cookies? It should not matter whether no or an incorrect cookie is sent back to the server. Still confused.

For testing could you try to get back into th

**Comment by bschmalhofer** [comment]
Also added _bin/docker/quick_setup.pl_ for more convenient development in OTOBO 10.0.x.

**Comment by svenoe** [comment]
Just as remark: I always login via http://server/otobo/index.pl, never https.

**Comment by svenoe** [comment]
Fixed. I also added a notice, if the wrong HttpType is set. I was thinking whether the notice was enough, as it solves the main problem of simply recognizing, that your setup is wrong. I delete both cookies now anyways, because, although this should almost never occur, it could be very tricky to tell all of your customers to delete their browser cookies themselves, if it does.

**Comment by bschmalhofer** [comment]
@svenoe : I see that in your fix you relied on the environment variable ``$ENV{REQUEST_SCHEME}`` . This is perfectly valid for rel-10_0, but problematic for rel-10_1. Generally, CGI  environment variables shoud be avoided. For being compatible with rel-10_1 there are two things to do:
- add the method ``Kernel::System::Web::Request::ServerProtocol()``. You can grab the implementation in rel-10_1.
- use that method in the interface modules

**Comment by svenoe** [comment]
Fixed for rel-10_1. :)

**Comment by wornet-aer** [comment]
I've just tried to migrate an OTRS v.6.0.5 to OTOBO 10.0.13 and observed exactly the same behaviour as described by this issue.

What I did:
1. Install fresh otobo-docker instance
2. Prepare OTRS files and db for migration
3. Execute OTOBO migration (all went through without errors)
4. Can't login because of: `Session invalid. Please log in again.` :(

Unfortunately it took me quite some time, until I found this issue. After deleting the old session cookie in Firefox the agent login works as expected.

Since this migration was only for testing purposes, I'll do another similiar migration in the next few days and can report back, if the error still occurs.
