### ISSUE TITLE
Bug recovery password

### ISSUE THREAD

**Issue by MrSipping** [RotherOSS/otobo#2567]
Hello, I know I should ask the community on the dedicated link, but could it be a bug? Don't they both use the same function? Because I don't understand how it can work on one side and not the other

**Comment by svenoe** [comment]
It most likely is not. OTOBO is used by quite some people, especially for more common functionality the likelihood of something not working at all is not too high. Of course there can be cases, but at the same time OTOBO is not the easiest piece of software to completely configure, and usually when people who are not really experienced with the program, or OTRS or Znuny encounter errors, it is due to configuration problems.
It still can be a bug, but even for our paid support customers, the first step if something doesn't work is, that some experienced supporter looks at the system and makes sure, that everything is configured right etc., before a developer looks at the code. This is just a resource issue, and as I said, I'm sorry, but we just cannot start searching for bugs, everytime someone encounters something which doesn't work for him.

(If you are very certain that you found a bug, then writing a bit more than "this does not work for me" is also helpful. At least a "can be reproduced by installing a clean OTOBO 10.1.8 (docker) and configuring this, this and that, if I do this, I encounter the following error" would be necessary.)
