### ISSUE TITLE
Remove Text::Diff::HTML from Kernel/cpan-lib

### ISSUE THREAD

**Issue by bschmalhofer** [RotherOSS/otobo#2610]
`Text::Diff::HTML`is loaded only in `Kernel::System::Diff` but not actually used there. Let's get rid of it.

**Comment by bschmalhofer** [comment]
Actually `Text::Diff::HTML` is used in `Kernel::System::Diff` as a styler that is loaded dynamically. But that style is set for the plain diff, which does not make sense at all. This is not critical at all, as `Kernel::System::Diff`is unused anyways. So let's go ahead with the removal.

**Comment by bschmalhofer** [comment]
Done. Diff.t looks fine. Closing this issue.

**Comment by bschmalhofer** [comment]
See also #1229

**Comment by stefanhaerter** [comment]
It was discussed wether `Text::Diff` can also be removed. There is one occurrence in core:

https://github.com/RotherOSS/otobo/blob/95a39de19fa50dd78aa8869f67b3b518d9ad606c/Kernel/Modules/AdminPackageManager.pm#L96-L98

https://github.com/RotherOSS/otobo/blob/95a39de19fa50dd78aa8869f67b3b518d9ad606c/Kernel/Modules/AdminPackageManager.pm#L109

https://github.com/RotherOSS/otobo/blob/95a39de19fa50dd78aa8869f67b3b518d9ad606c/Kernel/Modules/AdminPackageManager.pm#L120-L137

In order to remove `Text::Diff`, this would have to be rewritten. A suggestion by @bschmalhofer was to use `Algorithm::Diff`, which is already included as dependency of `Text::Diff`:

https://github.com/RotherOSS/otobo/blob/95a39de19fa50dd78aa8869f67b3b518d9ad606c/Kernel/System/Environment.pm#L283-L292
