### ISSUE TITLE
FR: Support for redis-cluster

### ISSUE THREAD

**Issue by pat-s** [RotherOSS/otobo#2838]
We're running a central `redis-cluster` instance which we would like to connect to OTOBO (running in Docker). This would need explicit support via https://metacpan.org/pod/Redis::Cluster::Fast, probably. 

I couldn't find a previous discussion for this, hence I am opening this as a feature request.

**Comment by bschmalhofer** [comment]
Hi Patrick,
as far as I know you are the first to inquire about Redis cluster. So this feature is not high up on the TODO list. But I don't think that this would be hard to do. For a proof of implementation I see the following steps:

- In otobo.web.dockerfile add the system package for Redis cluster, so that the header files from https://metacpan.org/release/PLAIN/Redis-Cluster-Fast-0.090/source/src/Fast.xs are found
- Edit: looks like the dependencies are included in the Perl module, this makes things easier
- Add Redis::Cluster::Fast in _cpanfile.docker_
- Copy _Kernel/System/Cache/Redis.pm_ to _Custom/Kernel/System/Cache/Redis.pm_
- Adapt the copied _Redis.pm_ to use Redis::Cluster::Fast
- As a quick and dirty workaround  hardcode your Redis server list in the copied _Redis,pm_
- Build a new local image
- test

But, as said above, I have no idea when this could be implemented.

**Comment by svenoe** [comment]
Added to enhancements and closed for the moment.
