### ISSUE TITLE
Use Frontend::WebPath for Customer/default/css/Core.Icons.css font uris

### ISSUE THREAD

**Issue by meinhart** [RotherOSS/otobo#2886]
When changing the Frontend::WebPath config to something different then default value "otobo-web" the changes won´t be reflected in var/httpd/htdocs/skins/Customer/default/css/Core.Icons.css file.

As result when trying to load Customer Dashboard there will be several warnings in the web console and the font´s can´t be loaded accordingly.
Error message: "Failed to decode downloaded font".

Possible fix: CSS Loader could check for urls and replace them with WebPath config value when loading to cache.

**Comment by bschmalhofer** [comment]
I think that this can be handled with a relative path. The file _Core.Icons.css_ is added to an compounded file, e.g. _CommonCSS_751303125ece5428c88f2e0d692cd9d4.css_. The browser fetches this file via an URL like . https://localhost:1484/otobo-web/skins/Customer/default/css-cache/CommonCSS_751303125ece5428c88f2e0d692cd9d4.css . This means that the absolute URL /otobo-web/common/fonts/ should also be fetchable via ../../../../common/fonts/.

TODO:

- [x] verify the error message not repaired installation of OTOBO 10.0.19
- [x] change absolute URLS to relative URLs
- [x] verify that the error disappears when loaded via different script pathes

**Comment by bschmalhofer** [comment]
In rel-10_0 I adapted the OTOBO code so that the static assets are available under the path _/otobo/assets_. Tested in Chrome whether the reported message can be seen. Directly loading _/otobo/assets/skins/Customer/default/css-cache/CommonCSS_7718b23fbf7a8e3ead491c8d037d3a16.css_ did not produce the message. But the message could be produced after logging on and opening a some random pages in the agent and in the customer interface. I suppose that there is lazy loading, and the font is only loaded when needed.

[change_web_path.txt](https://github.com/RotherOSS/otobo/files/14546238/change_web_path.txt)

**Comment by bschmalhofer** [comment]
Changed to relative pathes. Looks fine so far. PR is merged. Closing this issue.
