### ISSUE TITLE
Discuss coding standards

### ISSUE THREAD

**Issue by bschmalhofer** [RotherOSS/otobo#318]
Make some decisions about coding.

- [ ] where are the standards documented ?

- [ ] `unless` as a statement modifier 

- [ ] early return from subroutines

- [ ] using `my $Self = shift;` in subroutines

- [ ] using the return value of bless: `my $Self = bless {}, 'Class';`

- [ ] using `utf8::encode($String)` instead of `Encode::encode()`

- [ ] no parens with Perl builtin functions

- [ ] empty line before flow control statements:  exit, return, next, last, continue

- [ ] POD between `package` and firs `use` statement

- [ ] `1;` really in  the last line, after the POD

See also RotherOSS/doc-otobo-dev#27

**Comment by wollmers** [comment]
Just some comments as a contribution to the discussion, not a solution.

1) where are the standards documented ?

Good question. Should be easy to find and read.

2) `unless` as a statement modifier

Did a `grep -R unless ./Kernel`. Appears only in `./Kernel/cpan-lib`.

Personally I try to avoid `unless` unless [sic!] it's simple, obvious and reduces nesting levels.

3) early return from subroutines

Yes, leave the block as early as possible (cpmpares to next or last).

4) using my $Self = shift; in subroutines

What's the benefit? Or alternatives?

5) using the return value of bless: my $Self = bless {}, 'Class';

That's the usual way.

6) using utf8::encode($String) instead of Encode::encode()

Except `./Kernel/cpan-lib` it's only used in one place in an eval. This usage should be reviewed if it really does what it should (catch unassigned characters). Instead of `eval` the CHECK parameter could be used to catch errors.

7) no parens with Perl builtin functions

See no serious advantage. It's a matter of taste. Sometimes you need to add parens if code changes.

8) empty line before flow control statements: exit, return, next, last, continue

Yes.

9) POD between package and first use statement

IMHO easier at the end. Imagine a hotfix using Vim.

10) 1; really in the last line, after the POD

It's code and should be the last line of the code.

**Comment by svenoe** [comment]
•	Devel Handbuch und in CodePolicy anpassen
•	Nachgestellte conditions nur im Kontrollfluss (next, return, …)
•	Nachgestellte conditions dürfen maximal ein && oder || besitzen (sonst z.B. zwei next für ||, oder nicht nachgestellt)
•	unless ist verboten, außer in einfachen(!) nachgestellten conditions (statt next if !$x)
•	early return aus subroutines ist in Ordnung
•	my $Self = shift; ist erlaubt
•	my $Self = bless {}, 'Class'; ist erlaubt
•	Klammern sind für perl builtin functions nicht nötig
•	Leerzeile vor control flow statements für neuen code obligatorisch, wenn nicht einziges statement im Block
•	Bei längeren regex x-modifier und Dokumentation!
•	POD-Anfang: Erster POD-Block nach package/use/our, vor sub new {
•	1; als letztes statement, auch nach letztem POD

Encodings will be discussed elsewhere (or not)
