### ISSUE TITLE
DynamicField of Type Config Item fails to render links to other CI Items when there is more than one object.

### ISSUE THREAD

**Issue by jennypaxian** [RotherOSS/otobo#3607]
**Expected Behavior**
We are expecting that if we select multiple CI Classes in the Dropdown that we get shown a link to them, just as we would when only selecting one.
**Current Behavior**
The CI class names are shown but there is no formatting or linking happening.
**Context (Environment)**
OTOBO 11.0.1
**Detailed Description**
DynamicField of Type Config Item fails to render links to other CI Items when there is more than one object.

![1](https://github.com/user-attachments/assets/5691b2e8-732b-47f6-83e0-b56dd27af9b2)
![2](https://github.com/user-attachments/assets/30a61fdb-74cc-4d9c-a004-6b34b128371f)
![3](https://github.com/user-attachments/assets/42e787cb-e81e-4218-b383-b10be61c4870)

**Comment by svenoe** [comment]
Hi Jenny,

this is known and currently expected behavior. Not all functionality of the reference fields is available in multi-value context. (The technical reason here, is, that this displaying of values is existing code, which in general just shows single text or link blocks in various places. The multiple values are concatenated at a much earlier place.)

I will close this issue here and add it to a project which keeps track of potential enhancements to OTOBO, to keep the open issues halfway tidy. Likely we will not do this on our own in the near future as it is not a minor change in terms of necessary effort, although I agree, that it would be a helpful addition.

Best regards, Sven
