### ISSUE TITLE
<OTOBO_TICKET_DynamicField_Fieldname> for a DF Richtext doesn't parse the richtext

### ISSUE THREAD

**Issue by StefanAbel-OTOBO** [RotherOSS/otobo#3674]
When you use <OTOBO_TICKET_DynamicField_Fieldname> e.g. in a Process Transition Action for a Dynamic Field of type richtext, the result doesn't look good, as it is not parsed properly.
E.g. I have two dynamic fields, one (Name: Test) with the following content:
test

and one with the following content (Name: Dokumentation):
test
hallo

When I create an article with (ArticleCreate TransitionAction), it looks like this:
![Bildschirmfoto 2024-08-02 um 17 08 04](https://github.com/user-attachments/assets/49af19cf-a5fc-4b92-b1bd-0a0da1befa71)

This is the Body part of my ArticleCreate:
Dokumentation:<br/><OTOBO_TICKET_DynamicField_Dokumentation><br/><br/>Beschreibung:<br/><OTOBO_TICKET_DynamicField_Beschreibung_Value>

Tested on 11.0.4 on ov266

**Comment by stefanhaerter** [comment]
The observed behavior is due to

https://github.com/RotherOSS/otobo/blob/eac96d15a31901b5382497dd04716637f0c14f2a/Kernel/System/DynamicField/Driver/RichText.pm#L81

and

https://github.com/RotherOSS/otobo/blob/eac96d15a31901b5382497dd04716637f0c14f2a/Kernel/System/ProcessManagement/TransitionAction/TicketArticleCreate.pm#L321-L331

The TransitionAction code is in place since OTRS (5 years ago), and the behavior is used nowhere else - perhaps it was a planned feature. For a propper fix, the interactions with sysconfig setting 'Frontend::RichText' have to be considered.

**Comment by svenoe** [comment]
Not all dynamic fields have directly stringifyable content. This is even more so the case with references, sets, multivalue fields,...

At one point we certainly will have to think about how to handle all of them, including Richtext fields (and excluding Attachments, probably), but for now a Richtext field stores HTML and this is depicted in a way. I will put this into the OTOBO Enhancements project. Let's bring this up when planning for 11.1/12.0.
