### ISSUE TITLE
Review error handling and confirm usability of the email setup in installer.pl.

### ISSUE THREAD

**Issue by svenoe** [RotherOSS/otobo#375]
It was reported, that the email setup of the installer.pl may be dysfunctional. I had a quick look and noticed, that when I willfully produced errors, sometimes the whole AJAX process dies, which should not happen. This should be investigated altogether. See also: https://otobo.de/de/forums/topic/install-pl/

**Comment by svenoe** [comment]
Also see https://github.com/RotherOSS/otobo/issues/1127

**Comment by svenoe** [comment]
And probably #456

**Comment by StefanRother-OTOBO** [comment]
Hi,
This error still exists, you just have to configure POP/IMAP and SMTP in the installer, this is currently not possible.

**Comment by stefanhaerter** [comment]
As far as I have currently investigated, the issue consists of two parts:

- Kernel/System/Email/SMTP::Check relying on $Param{CommunicationLogObject}, which is only given once in the Send function of the same file (grep '\->Check' -R Kernel/)
- It is mandatory to provide inbound and outbound mail configuration

The latter can be treated easily with wrapping the checks into if-Blocks. For the first one I would suggest to check for an existing communication log object in the Check function and to create one if missing, analogously to #2098 .

**Comment by stefanhaerter** [comment]
Note for development: For some reason, FQDN isn't set when Kernel/System/Email/SMTP::Check() is run, even though ist should be.

**Comment by stefanhaerter** [comment]
It shows that there is another bug involved which affects both Sendmail and SMTP:
https://github.com/RotherOSS/otobo/blob/b88f937a82f6de79f27a8f1b4d4485dbb447d434/Kernel/System/Email.pm#L797-L811

The Check function relies on the attribute `Successful` in the data returned from either backend, but both backends return `Success` in its data. I propose to change the behavior in `Kernel/System/Email.pm`, since the Check function of this file is only called once in `Kernel/Modules/Installer.pm`.

**Comment by stefanhaerter** [comment]
So far, the changes seem to work except Sendmail in docker, which is due to the fact that docker doesn't have the sendmail binary per default (at least not at /usr/sbin/sendmail and according to @bschmalhofer not at all). Suggestion is to hide the option Sendmail in the dropdown under docker.

**Comment by stefanhaerter** [comment]
Fixed with #2120
