### ISSUE TITLE
Layout: Country input field in AdminCustomerCompany

### ISSUE THREAD

**Issue by bschmalhofer** [RotherOSS/otobo#385]
The input fields are arranged in a nice way. But the input field for the country sticks out, as it is longer than the other fields.

**Comment by bschmalhofer** [comment]
The other select field, Validity, is shorted than the text fields.

**Comment by bschmalhofer** [comment]
This is still the case. Leaving this issue open.

**Comment by stefanhaerter** [comment]
Due to the use of outerWidth() in https://github.com/RotherOSS/otobo/blob/0f1ef96fc5c8d14e80d70378cd0c720a8cbb7617/var/httpd/htdocs/js/Core.UI.InputFields.js#L1335, this seems to be related to #1641. The reason is that, to my best knowledge, outerWidth() does not work reliable on hidden elements (the select is hidden at this point of initialization).

**Comment by stefanhaerter** [comment]
It may seems a bit odd, but a test which I did showed that the length of the select field in the end depends on the length of the select options here. The valid field is only 140px long because its longest option is 'invalid-temporarily'. The country field is 340px long because its longest option is 'United Kingdom of Great Britain and Northern Ireland'.

Currently, I have no fair solution at hand to secure the fields to be equally long. @bschmalhofer @svenoe is this worth a discussion? If not, I would suggest to close the issue.

Edit: Here is a patch which I used to test my hypothesis. It enlargens the valid field considerably.

[select_length_test.patch.txt](https://github.com/RotherOSS/otobo/files/12728352/select_length_test.patch.txt)

**Comment by stefanhaerter** [comment]
For select fields, the general concept for widths is to adjust according to the option's content. We changed this for ticket input masks, but it can make sense for single fields in the admin interface. Maybe, at one point, we can globally rework the input field css. Until then, for the admin interface, no changes will be made.
