### ISSUE TITLE
[BUG] Update REL_11_0_6 - no CKEDITOR visible

### ISSUE THREAD

**Issue by md-esw** [RotherOSS/otobo#3877]
### Environment

- Server OS Distribution: Debian 12
- OTOBO installation typ: Docker
- Browser: Firefox
- OTOBO version: rel_11_0_5

### Expected behavior
Clear Update to new version.

Wanted to do the security patch.

### Actual behavior
After the update with docker package to rel_11_0_6 i have no editor visible in Otobo.
Some error codes in the Update script behaviour:

"No packages for your framework version 11.0.6 found in this repository"

### How to reproduce

Update to rel 11_0_6

### Additional information

No Editor there

### Screenshots
![grafik](https://github.com/user-attachments/assets/9d2bf883-3cb3-478b-a280-60a879ea09d8)

**Comment by svenoe** [comment]
Hi md-esw,
this is not the case for our systems. Please delete your browser cache (if this helps, check whether you have Loader::Enabled:JS disabled), check your SysConfig options which change js files loaded, if those are changed, they are not automatically updated, check your addons, and your browser error log for messages there. For further questions, please first visit our [forums](https://otobo.io/forums/otobo/otobo-forum/), I'm quite sure that this is not an OTOBO bug, and for general questions and community support this is the right address. (If you need professional support, you can also write an email to hello@otobo.io.)
Best regards, Sven

**Comment by md-esw** [comment]
Your comment is not really helpful. It has nothing to do with caching or something, its just a problem with updating...

General professional support for a problem during update? No, thanks!

**Comment by svenoe** [comment]
1. This problem does not occur on updates on systems with standard configuration. (We have performed more than one.)
2. Browser cache can be a problem, because quite some js changed together with some CK5-Editor changes, and what you experience is this js not being executed properly.
3. You're welcome using an open source tool for free. You are having some troubles which are not reproducible on a vanilla system. I gave you some hints and told you where you might get help from the community - if you expect us to invest time onto your personal problem for free, too, then maybe rethink your picture on your position and how this stuff works in general...good luck.

**Comment by md-esw** [comment]
Hi again, after update to 11.0.7 CKEditor still not in every mask there - just html.

Any Help for this issue?

**Comment by svenoe** [comment]
We don't offer individual support on github, as also written in #3690.

**Comment by md-esw** [comment]
> We don't offer individual support on github, as also written in #3690.

but its a problem and nobody helps. I think i should call a problem here? Or not? It makes no sense to unpublish bugs?

**Comment by svenoe** [comment]
It is not necessarily a bug if something is only affecting yourself. It's not reproducible on a vanilla system, as I said, and there are too many things you can have set up erroneously.
And come on, with your rants, it should not be surprising that the motivation to spend time on this is not too high, either. Nobody is obliged to help.
