### ISSUE TITLE
System configuration help button

### ISSUE THREAD

**Issue by joserribeiro26** [RotherOSS/otobo#398]
There is a small and not critical problem with the help button, in the system configuration. Nothing that impacts the functioning of the system.

<img width="219" alt="Screenshot_7" src="https://user-images.githubusercontent.com/475022/91357959-69a33300-e7c8-11ea-81de-bab6bbd2443c.png">

**Comment by svenoe** [comment]
Hi José,

thank you  for your contribution.

Some questions:
1. I assume you are on OTOBO 10.0.1 or later, and are not using a beta version anymore? (We had this behaviour a while ago, but at least for our systems it is fixed.)
2. Which browser are you using?
3. Do you, by chance, have a package with a very long name installed? (If you click on the package list, where in your picture "OTOBO" is selected.)

<img width="275" alt="grafik" src="https://user-images.githubusercontent.com/48322755/91439339-133c0000-e86d-11ea-86fc-de67d831d7cb.png">

**Comment by joserribeiro26** [comment]
Hi,
Yes, the version installed is the latest 10.0.2.
I have only the standard packages.

![image](https://user-images.githubusercontent.com/475022/91443398-ab27f280-e849-11ea-9dcf-b20b4a04a0cc.png)

My  screen resolution 1920x1080 with zoom 150%

![image](https://user-images.githubusercontent.com/475022/91443956-6e103000-e84a-11ea-9ce7-e1e279c58cc6.png)

**Comment by svenoe** [comment]
Hmm...I don't think it's connected to the scaling of the monitor (to be sure, I clicked through some different scalings for mine, too, and it did not change the position of the button).

I assume it's browser specific and/or connected to fonts and their sizes. Could you tell me which browser you are using?

---

If you are up to some debugging, I would also be interested in the following:

If you right click on the input field next to (or above in your case) the help button, most browsers will give you an option like "Inspect", "Inspect Element", or similar. If you click this, mostly there are some ways to find out the exact sizes of all elements.

For me, using firefox, the input box for example looks like this:
<img width="978" alt="grafik" src="https://user-images.githubusercontent.com/48322755/91448722-84ce7b00-e87a-11ea-9a9d-33190e0ed6fc.png">
<img width="406" alt="grafik" src="https://user-images.githubusercontent.com/48322755/91448770-96b01e00-e87a-11ea-90ab-3b3f25b5dea6.png">

or even more detailed
<img width="341" alt="grafik" src="https://user-images.githubusercontent.com/48322755/91448841-adef0b80-e87a-11ea-8e74-cf20f8c9eb84.png">


The button itself looks like this:
<img width="480" alt="grafik" src="https://user-images.githubusercontent.com/48322755/91448956-d4ad4200-e87a-11ea-982a-dfb5ff20adaa.png">
<img width="201" alt="grafik" src="https://user-images.githubusercontent.com/48322755/91448971-da0a8c80-e87a-11ea-8b53-7121e5de705f.png">

I would be interested how both sizes are on your side.

---

Additional note: The package names take up more space in the selection dialog for José, compared to me. This is however not directly the reason.
<img width="280" alt="grafik" src="https://user-images.githubusercontent.com/48322755/91449503-7fbdfb80-e87b-11ea-85c2-c86fa207666e.png">

**Comment by joserribeiro26** [comment]
See if this information helps you.

![image](https://user-images.githubusercontent.com/475022/91453055-af5a0d00-e855-11ea-8461-7d44c2a63097.png)


![image](https://user-images.githubusercontent.com/475022/91453136-c3057380-e855-11ea-8981-b3997c0a02dc.png)

**Comment by svenoe** [comment]
Ok, after looking again more closely, the problem is clear, I still don't know where it comes from, however:

Comparing both images, you have an additional margin or padding left of the input field.
<img width="61" alt="grafik" src="https://user-images.githubusercontent.com/48322755/91459778-560ad180-e887-11ea-835d-aa4b20405fd5.png"> <img width="46" alt="grafik" src="https://user-images.githubusercontent.com/48322755/91459820-6327c080-e887-11ea-88bc-e039cc625c2f.png">

I will have to look through the packages and some newer commits, whether some side effects were overlooked, somewhere. Since I so far could not reproduce it, by installing different packages and so on, you could greatly help me, by doing the following. Only if it fits for you, however! (Doing only some of the points, would help, too.)

1. In your browsers inspector (the html code, when inspecting elements), hover over the parent elements of the input field, to see if you find, which element contains the additional padding or margin (should be displayed green or orange, left of the field).
2. In the Styles tab, where in your above pictures the layout is shown (Computed tab selected), you should be able to find the rule, which encodes this margin or padding (there probably is something like 20px, or maybe 24px, or so). If you could just copy the whole text which is shown there, it would be nice.
3. If you have fun doing this ;) - if you search for "Loader::Enabled::CSS" in the SysConfig, you could for a moment deactivate it, clear your browser cache, redo steps 1. and 2., and in step 2., when you found the rule, you should be able to tell me, which file it is in. (After that, enable the CSS loader again.)

If you don't have time for all of this, it's ok, I will try to find it in any case. And thanks again for your help so far. :)

**Comment by joserribeiro26** [comment]
Daylton who works here with me will help us :-)

**Comment by joserribeiro26** [comment]
This works normally for me now.
