### ISSUE TITLE
[BUG] entrypoint.sh: 'cp --archive' Operation not permitted

### ISSUE THREAD

**Issue by yahikii** [RotherOSS/otobo#3997]
### Environment  
- **OTOBO installation type:** Kubernetes (AWS)  
- **OTOBO version:** 11.0.7  

### Expected behavior  
The `copy_otobo_next` script from `entryscript.sh` runs successfully without errors.

### Actual behavior  
The script fails when running the `cp --archive` command due to missing root privileges. This happens because `/opt/otobo` is mounted as a Persistent Volume Claim (PVC) in Kubernetes, and the top-level directory of the PVC therefore is  owned by uid `root`and gid `otobo`. As a result, the `--archive` flag, which also preserves timestamps, causes a permission error.

### How to reproduce  
1. Install OTOBO on Kubernetes and mount `/opt/otobo` as a PVC.  
2. Run the `copy_otobo_next` script.  
3. Observe the failure when the script tries to execute `cp --archive`.

### Additional information  
We implemented a workaround by replacing the failing command:  
```bash
cp --archive otobo_next/. otobo_home/  
```

with:
```bash
cp --recursive --no-dereference --preserve=links,mode,ownership otobo_next/. otobo_home/  
```

This resolves the issue but avoids preserving timestamps.

Below is the error code we get, when using the cp command with the parameter --archive:

```bash
cp: preserving times for '/opt/otobo/.': Operation not permitted
```

### Question:

Does Otobo rely on the file timestamps copied by cp --archive? If not, would it make sense to adjust the script to avoid preserving timestamps, which would prevent this issue for Kubernetes users or similar restricted environments?

Thank you already for your answers and help!

**Comment by bschmalhofer** [comment]
Hi @yahikii ,

it es very nice to see that OTOBO is being used with Kubernetes in AWS.

I try to answer you question about the timestamps. Modification time of files are used in some places in OTOBO. A quick search for mtime gave me:
-  Kernel/Output/HTML/Layout/Loader.pm -    for cached js and css files
- Kernel/Output/Template/Provider.pm   -    likely for caching template processing
- Kernel/Config/Defaults - method ConfigChecksum() seem to be unused, see #1327
- Kernel/System/ModuleRefresh.pm - for detecting changed Perl modules
- maybe more

All these detect file changes that are caused by running OTOBO. So I would expect that they would be independent of the initial timestamp that came from `copy_otobo_next`. In order to verify that guess, I'll run the test suite, on a non-Kubernetes installation, with your proposed changes.

I am hesistant in changing that generally in OTOBO though. Experience shows that making seemingly harmless changes can have serious repercussions.

We are also aware of the underlying problem. OTOBO has poor separation of static and dynamic files. Almost all of the files that are copied by `copy_otobo_next()` could stay as static files in the Docker image itself. But that is not how OTOBO has evolved historically.

**Comment by StefanRother-OTOBO** [comment]
Hi @yahikii,

two short questions: 
Do you use S3 Storage for the temp. files Bernhard mentioned?
Do you create helm charts, for OTOBO Kubernetes?

Thanks and merry Christmas,

Stefan

**Comment by yahikii** [comment]
Hello,
thank you both so much for your answers already. Actually I already found a solution while browsing through the other projects you have. I came across your old Otobo Kubernetes project and saw that you used a subpath for the pvc. I added this to my dev environment and it indeed solved my issue. Because of that I would close this issue and there is no further action needed.

For other people who will maybe have the same issue and search a solution for it, you have to add a subpath to the volumeMounts for /opt/otobo like below:
https://github.com/RotherOSS/otobo-kubernetes/blob/55b9d348d48d47aa5d664693ca2ef470e79ebbc0/Config/yaml/web-deployment.yaml#L48

Thank you again for your help though! :)

**Comment by bschmalhofer** [comment]
Thanks @yahikii for digging up the workaround with the subpath.

Just for the record. I ran the testsuite with the following adaption:

```
diff --git a/bin/docker/entrypoint.sh b/bin/docker/entrypoint.sh
index c6dbbd3bdb..c289f21f75 100755
--- a/bin/docker/entrypoint.sh
+++ b/bin/docker/entrypoint.sh
@@ -148,7 +148,7 @@ function copy_otobo_next() {
     # Changed files are overwritten, new files are not deleted.
     # File attributes are preserved.
     # Copying $otobo_next/. makes it irrelevant whether $OTOBO_HOME already exists.
-    cp --archive $otobo_next/. $OTOBO_HOME
+    cp --recursive --no-dereference --preserve=links,mode,ownership otobo_next/. otobo_home/ $otobo_next/. $OTOBO_HOME
 
     {
         date

```

No new test failures surfaces. So not preserving the file dates would be an option too. But I would prefer to stick with `--archive`.
