### ISSUE TITLE
Use irand instead of int rand in Main.pm.

### ISSUE THREAD

**Issue by svenoe** [RotherOSS/otobo#406]
According to https://metacpan.org/pod/Math::Random::Secure this should be faster. Kernel/System/Main.pm uses int rand in sub GenerateRandomString.

**Comment by bschmalhofer** [comment]
@svenoe , while you are at it cou convert the sub to calling  Math::Random::Secure::irand() only once and then convert the result to base 62, that is to a string containing only the 62 characters in `[0-9][a-z][A-Z]`.

**Comment by svenoe** [comment]
Yes, I thought about that, although you can call this for variable dictionaries and string lengths, and so some calculating has to be done, and one time won't be enough, if your string exceeds 32bit of information, as I understand it.

**Comment by bschmalhofer** [comment]
I also noted that the namespace `Kernel::System::Main` is not very clean. Various subroutines are imported into the namespace which are subsequently available as methods on the Main object. `use namespace::autoclean;`can do the cleaning up. This module is not a new dependency, as it is already implicitly required because of the module `Moo`. See also http://perladvent.org/2011/2011-12-03.html.

**Comment by bschmalhofer** [comment]
Tests look fine. Closing the issue.
