### ISSUE TITLE
Kanboard Integration to OTOBO

### ISSUE THREAD

**Issue by KriegerV** [RotherOSS/otobo#465]
At this stage, OTOBO is a little bit poor regarding Agile topics. It could be great to make the tool more ready for PI and Agile ceremonies. One first step could be to work on the integration of Kanboard in OTOBO that takes as task specific tickets.
Kanboard columns could be OTOBO dynamicfields or OTOBO ticket status. Thus moving a ticket from a column to another updates the ticket field.

**Comment by svenoe** [comment]
Hi Vincent,

we again talked a bit about this. The thing is, that we don't see OTOBO as project management tool so much, at the moment. When talking about a Kanboard, I guess in the end, you would rather not only have a board which visualizes the state of a set of tickets, but you would want some interactivity, the possibility to open tickets from there, and so on. This would quickly become quite large of a project, I assume. I will add this as possible addition for the future anyways, because it definitely is interesting, and if you would like to, you can definitely add a more concrete plan of what you would have in mind, the needed functionality and so.

For now in any case, I think there are three options. The easiest would probably be, to see, whether the change management module of the ITSM-package fits your needs, which can be used to plan bigger projects, define tasks like reviews after implementation, etc., but is probably less flexible compared to a Kanboard. Secondly one could think about developing an interface between a third party software featuring a Kanboard and OTOBO (tasks moved to a "Todo"-column in the Kanboard could automatically open up a ticket; closing a ticket would automatically move the task in the Kanboard and so on), here I don't have a good overview over tools which are frequently used. Third (could be true for the second option, too, which is just less work), you could consider to hire us, to develop those features for you.

Thanks again for participating and suggesting things, hopefully you are not discouraged, especially at the moment, we just have quite a lot of other tasks and projects... :) 

Sven

**Comment by joserribeiro26** [comment]
We have a Kanban developed for OTRS, I believe that with little effort it could be ported to OTOBO, if it is of interest we could give this product to be inserted in the OTOBO code.

**Comment by svenoe** [comment]
At least having it as package would definitely be interesting. We are currently thinking about enabling third parties to provide their own package repositories via the OTOBO package manager. But that is not yet totally thought through. In the end I at least see it as a good way that in cases like this one, not everything has to be directly handled by us, and also it would be easier to recognize, who is contributing,...

Regarding this package - in principle some packages can be converted straight forward by using:
bin/otobo.Console.pl Dev::Tools::Migrate::OTRSToOTOBO --cleanall --target TargetDirectory Package.opm

José, it is mostly up to you, how you want to handle this at the moment. I think within the next three or four weeks, our schedule is too busy, to start testing those additional requests, especially as we would have to figure out the supposed functionality first and so on, but we are happy of course, if independently of us, packages for otobo are built and distributed. As I said, our goal is, to provide a way of doing this nicely via custom Repos at one point.
