### ISSUE TITLE
DateTime issue in current 10.1.

### ISSUE THREAD

**Issue by svenoe** [RotherOSS/otobo#547]
Currently, when trying to execute Maint::Cache::Delete e.g., I get the following error:
`Initialization of state variables in list context currently forbidden at /media/sf_dev/otobo/otobo-dev/Kernel/System/DateTime.pm line 1619`
And I'm not sure, for what reason we use state here.

**Comment by bschmalhofer** [comment]
`state` is used here as the modern replacement for the caching Variable `%ValidTimeZones` which was previously declared in file scope. The problem was that assignment of state hashes is only supported in Perl 5.28 or later. See https://www.effectiveperlprogramming.com/2018/08/initialize-array-and-hash-variables-with-state/.

I changed the implementation to using a scalar instead of a hash as the state variable. Closing the issue.
