### ISSUE TITLE
Document / Improve restore.pl procedure

### ISSUE THREAD

**Issue by ict** [RotherOSS/otobo#628]
Hello there,

We are currently running a Docker-deployed OTOBO installation.

To set up a staging system (and as a test for the backup script), I wanted to clone the system to another server. While I have now succeeded, the process turned out to be a bit complicated and not well documented. The steps that finally led to success where as follows, please correct me if those were unneccessarily complicated:

1. Create a backup using `scripts/backup.pl`
2. Spin up a new `docker-compose` deployment on another server. Since this was supposed to be a testing environment, I chose another database root password in the `.env`.
3. Go through the whole `installer.pl` procedure to set up the database information inside the new installation.
4. Manually `DROP DATABASE otobo` and re-create the database, using the scheme from e.g. https://github.com/RotherOSS/otobo/blob/df1720b4b1419fc032aa7b57cb489f12214e926d/bin/docker/quick_setup.pl#L363
5. Run `restore.pl`
6. Manually change the `otobo` database user password (because I forgot to note it down during initial installation) and change it accordingly in `Config.pm`
7. Finally log in

And finally, some improvement suggestions:

1. In `restore.pl`, do all the checking first before starting the process. It happened multiple times that the script already overwrote `/opt/otobo` with the backed up data but then errored out because the database user password was wrong, leaving the system in a very broken state.
2. The database state required to import the backup (empty database exists, credentials are read from OTOBO) is never possible to exist without manual intervention. Either you have a freshly spun up docker installation, then there is no database user and database. Or you have a running installation, then there are already tables. Maybe provide different command line switches to drop the tables or to import into a new database.
3. Please document how to recover from e.g. a total system loss when you have backups made from `backup.pl`.

Thanks for coming to my TED talk ;)
Best regards
Demian

**Comment by StefanRother-OTOBO** [comment]
Hi Demian,

I hope you are well and healthy!

the scripts backup.pl and restore.pl were originally developed to be able to restore an older OTOBO version, if the current version contains errors, that cannot be solved.

Regarding the process I would proceed as follows:

1.) Create a backup using `scripts/backup.pl`
2.) Spin up a new docker-compose deployment on another server.
3.) Login to the mysql console via docker `root>docker exec -it otobo_db_1 mysql -uroot -p'RootPasswordFrom.EnvFile'`,
create a new database `mysql> CREATE DATABASE otobo CHARSET utf8mb4;`,
create the otobo database user `mysql> CREATE USER 'otobo'@localhost IDENTIFIED BY 'ExistingOTOBOPassword';`,
set database permissions `mysql>GRANT ALL PRIVILEGES ON 'otobo'.* TO 'otobo'@localhost;`,
flush privileges `mysql> FLUSH PRIVILEGES;`.
4.) Run `scripts/restore.pl`.

I will test the whole procedure at the next opportunity and in the next step I update our documentation so that it is clearer how to move the system.

I see your other improvement suggestions in the same way. We will fix this behavior in one of our next releases. If you have some special wishes, feel free to add details here.

Thanks very much for your help!

Stefan Rother
Team OTOBO

**Comment by ict** [comment]
Hi Stefan,

thank you, I'm fine. Hope your are as well 👍 

Yes, I think the biggest problem was me choosing a new database password, this breaks the restore. If you keep the password for the `otobo` database user (and you remember it from the old installation), then your process should work.

Maybe add a little hint on how to recover it to the final documentation.
