### ISSUE TITLE
A patch level update overwrites CustomerAccept.tt

### ISSUE THREAD

**Issue by bschmalhofer** [RotherOSS/otobo#739]
It is recommended practice that CustomerAccept.tt is adapted to the needs of the installation of OTOBO. But a patch level update would overwrite the changed file.
The proper way to handle this would be to create a OTOBO package containing the changed CustomerAccept.tt . A simpler option would be to first copy _Kernel/Output/HTML/Templates/Standard/CustomerAccept.tt_ to _Custom/Kernel/Output/HTML/Templates/Standard/CustomerAccept.tt_ and only edit the custom copy.

**Comment by svenoe** [comment]
In my opinion file changes like this, regardless of whether a package is built, or not, should be done in _Custom/Kernel/Output/HTML/Templates/MyCustomTheme/xxx.tt_, and then the "DefaultTheme" in the SysConfig should be set to this. This way one has the cleanest separation between the default files of OTOBO, files which are changed because of more general packages, and very specific, local adaptions to OTOBO, which are packed together at one place, regardless of whether they are also bundled into a package or not.

(The recommendations should definitely not be, to simply overwrite _Kernel/Output/HTML/Templates/Standard/CustomerAccept.tt_, I agree - where are they?)

**Comment by bschmalhofer** [comment]
See also #1281

**Comment by bschmalhofer** [comment]
@svenoe Is this issue resolved with the changes done for #1467 ?

**Comment by svenoe** [comment]
> @svenoe Is this issue resolved with the changes done for #1467 ?

Yes, it is.
