### ISSUE TITLE
Adjust the code in rel-10_0 branch to work with CodePolicy.

### ISSUE THREAD

**Issue by svenoe** [RotherOSS/otobo#760]
While introducing and adapting CodePolicy to our likings there will be code changes on OTOBO at the same time. See also https://github.com/RotherOSS/CodePolicy/issues/2

**Comment by bschmalhofer** [comment]
The Perl::Critic failures are now down to eight files.
Determined with `../CodePolicy/bin/otobo.CodePolicy.pl  --plugins +TidyAll::Plugin::OTOBO::Perl::PerlCritic -a 1>critic.out
`
There are some case I don't understand. The relevant lines have been marked with TODO-comments:

Kernel/System/MigrateFromOTRS/CloneDB/Driver/Base.pm
Kernel/System/MigrateFromOTRS/OTOBOCopyFilesFromOTRS.pm
Kernel/System/MigrateFromOTRS/OTOBOOTRSConnectionCheck.pm
Kernel/System/UnitTest/RegisterDriver.pm
Kernel/System/UnitTest/Selenium.pm
Kernel/System/UnitTest/Selenium.pm
Kernel/System/Web/Exception.pm
scripts/backup.pl

These cases have been fixed by changes in the CodePolicy. The TODO-comments have been removed.

**Comment by bschmalhofer** [comment]
The policy https://metacpan.org/pod/Perl::Critic::Policy::ValuesAndExpressions::ProhibitCommaSeparatedStatements might hint at real errors. Make sure that there are no violations of that policy.

**Comment by bschmalhofer** [comment]
Only a single Perl::Critic violation is left now. This violation is covered by https://github.com/RotherOSS/CodePolicy/issues/30.

**Comment by bschmalhofer** [comment]
There are still some violations from OTOBO::Perl::ObjectDependencies;
```

[checked] Kernel/System/MigrateFromOTRS/CloneDB/Backend.pm
[33mTidyAll::Plugin::OTOBO::Perl::ObjectDependencies[0m
[31mThe following objects are used in the code, but not declared as dependencies:
    'Kernel::Language',
[0m

```

**Comment by bschmalhofer** [comment]
The next step is to go through the violations of OTOBO::ProhibitOpen. These popped up due to https://github.com/RotherOSS/CodePolicy/issues/26. See https://perlmaven.com/open-and-read-from-files for the best practice of using `open`.

**Comment by bschmalhofer** [comment]
Down to 3 failures:
```
bes:~/devel/OTOBO/otobo (issue-#760-satisfy_more_policies)$ ../CodePolicy/bin/otobo.CodePolicy.pl -a > policy_14.out

Error: 3 file(s) did not pass validation.
 - Kernel/System/Ticket/Event/NotificationEvent/Transport/Email.pm
 - Kernel/System/Calendar/Event/Transport/Email.pm
 - Kernel/System/MigrateFromOTRS/CloneDB/Backend.pm
```

The failures for the two Event modules are covered by https://github.com/RotherOSS/CodePolicy/issues/44. One failure still open.

**Comment by bschmalhofer** [comment]
Accepted the violation of TidyAll::Plugin::OTOBO::Perl::ObjectManagerCreation in _Kernel/System/MigrateFromOTRS/CloneDB/Backend.pm_. This leaves two violations that are covered in an existion issue. Closing this issue when the PR for #1000 is merged and when there are no new violations.

**Comment by bschmalhofer** [comment]
Checked the Codepolicy for the rel-10_0 and the issue-#1000-zzz_reload branches. Looks good. Closing this issue and open one for the rel-10_1 branch.
