### ISSUE TITLE
Running OTOBO in the plesk = docker panel

### ISSUE THREAD

**Issue by frankii91** [RotherOSS/otobo#767]
Your containers are not properly made to run with Plesk (and their built-in Docker mechanism), so there is no clear instruction for that, and I think a lot of people use Plesk. I did not succeed, the containers do not start, no logs

**Comment by StefanRother-OTOBO** [comment]
Hi frankii91,

I hope you are well!

We have not yet tested our Docker and Docker Compose containers under Plesk. However, the OTOBO containers should run in all Docker environments if configured correctly.

Since OTOBO is 100% free of charge and open source, we currently see the following possibilities to meet your requirements in the short term. 

1.) You help to fix the problems and we integrate your findings into the OTOBO standard so that it can be used in the future.

2.) You commission us to recreate the situation and update and document the containers for use under Plex, thus supporting the OTOBO open source project. If this is of interest to you, please feel free to send us a message to hello@otobo.de and we can discuss the details afterwards.

Alternatively, we will definitely put your request on our "Wishes" list to prioritise the topic for further OTOBO releases.
As this is not currently an OTOBO issue, we will close this case. I hope for your understanding.

Thanks very much for your help!

Stefan Rother
Team OTOBO
