### ISSUE TITLE
Migration OTRS PostgreSQL to OTOBO PostgreSQL

### ISSUE THREAD

**Issue by StefanRother-OTOBO** [RotherOSS/otobo#818]
The PostgreSQL to PostgreSQL migration failed. However, it then went through after the following changes were made:

We adjusted the file /opt/otobo/Kernel/System/MigrateFromOTRS/CloneDB/Driver/Base.pm:

Before:

my $TrunkateSuccess = $TargetDBObject->Do( SQL => "TRUNCATE TABLE $TargetTable" );

After:

my $TrunkateSuccess = $TargetDBObject->Do( SQL => "TRUNCATE TABLE $TargetTable CASCADE");

To be included in the standard, we need to include the function in postgresql.pm so that we don't compromise MySQL.

Thanks!

Stefan

**Comment by bschmalhofer** [comment]
This is a bit tricky. One goal of the code is that migration works in the same way under both MySQL and PostgreSQL. Simply adding 'CASCADE' might violate that principle. Under PostgreSQL, calling `TRUNCATE TABLE dummy CASCADE` truncates the table _dummy_ and all tables referencing _dummy_. This would make it different from `TRUNCAT TABLE dummy_` under MySQL. In real life this difference is usually not significant as the tables are all truncated anyways.

The line in question is located in Base.pm, this means that it is executed on both  MySQL and PostgreSQL. The aim of the code is to make sure that the table in the OTOBO database is empty before adding content from an older database.  Per default, 'TRUNCATE TABLE' behaves the same way under MySQL and PostgreSQL. The table is not truncated when there are dependent tables. And it is expected that there are dependent tables. In order to evade that behaviour, the attribute _DeactivateForeignKeyChecks _ is passed when creating the target database handle. This attribute causes code to be run when a connection is established. AFAIK this works fine under MySQL.

- MySQL:  `SET FOREIGN_KEY_CHECKS = 0`
- PostgreSQL: `set session_replication_role to replica;`

In PostgreSQL 11 there is known bug that prevents this from working when TRUNCATE is used:   https://www.postgresql.org/message-id/15657-f94bb6e3ad28e1e2%40postgresql.org .

IMHO there are two main options:

1. accept the divergent behavoir of 'TRUNCATE TABLE ... CASCADE'
2. for PostgreSQL replace 'TRUNCATE TABLE dummy CASCADE`with `DELETE FROM dummy` 

I would argue for 2. .

@StefanRother-OTOBO  What is your opinon?

**Comment by StefanRother-OTOBO** [comment]
Hi Bernhard, 

I have no preference at the moment, I don't have enough postgreSQL knowledge. Please feel free to implement the solution you suggest.

Thanks very much!

Stefan

**Comment by bschmalhofer** [comment]
Implemented the second alternative. Merged the PR and closing this issue.

**Comment by bschmalhofer** [comment]
@kess-net : Sorry, I wanted to pass this issue on to you, but then I realised that the issue was already closed.

**Comment by kess-net** [comment]
On Fri, 30 Apr 2021 03:55:36 -0700
Bernhard Schmalhofer ***@***.***> wrote:

> @kess-net : Sorry, I wanted to pass this issue on to you, but then I
> realised that the issue was already closed.
> 

kein Problem :-)

Ich wünsche noch ein Schönes Wochenende.
