### ISSUE TITLE
migration.pl ignores OTRS Tags in the ITSM ChangeManagement Notification

### ISSUE THREAD

**Issue by OlliW** [RotherOSS/otobo#883]
migration.pl ignores OTRS Tags in the ITSM ChangeManagement Notification

**Comment by bschmalhofer** [comment]
Hi @OlliW,

first a question because I'm not really familiar with upgrading and migrating the ITSM package. How did you transfer the ITSM related data from OTRS to OTOBO? I think that migration instructions for ITSM is missing in https://doc.otobo.org/manual/installation/stable/en/content/ and that the ITSM tables are not handled in migration.pl.

When the ITSM tables are available then a quick fix for the notifications should be a simple SQL statement in the OTOBO database.

`
UPDATE change_notification_message SET text = REPLACE( text, '<OTRS_', '<OTOBO_');
UPDATE change_notification_message SET text = REPLACE( text, '&lt;OTRS_', '&lt;OTOBO_');
`
Could you try those and report whether these statements work for you?

**Comment by bschmalhofer** [comment]
Fiddled a bit with the migration modules. Added a module for migrating the ITSM tables. But the real problem is finding a good test case where this can be tested.

TODO:

- [x] testmigration with actual data
- [x] find out whether change_notification_message really is the only table that needs to be migrated

**Comment by bschmalhofer** [comment]
Found no further ITSM tables that contain macros like '<OTOBO_'. A test migration looked fine.

Merged the PR as it has some simplifications of the migration modules.

@svenoe There is a new migration task OTOBOItsmTablesMigrate which is current activated. However, the task is still untested, as my source database doesn't have ITSMChangeManagement installed. I propose that we deactivate the new task, unless we manage to do a meaningful test migration of an installation that actually uses change management.

**Comment by bschmalhofer** [comment]
Did a testmigration from Znuny 6.0, PostgreSQL to OTOBO 10.0, Mysql with ITSMChangeManagement installed, but no actual changes. The migration result looks fine:

Source OTRS:

> otrs=> select count(*) from change_notification_message where text like '%OTRS\_%';
>  count
> -------
>    216
> (1 row)
> 
> otrs=> select count(*) from change_notification_message where text like '%OTOBO\_%';
>  count
> -------
>      0
> (1 row)
> 
> otrs=> 
> 

Target OTOBO:
> MariaDB [otobo]> select count(*) from change_notification_message where text like '%OTRS\_%';
> +----------+
> | count(*) |
> +----------+
> |        0 |
> +----------+
> 1 row in set (0.006 sec)
> 
> MariaDB [otobo]> select count(*) from change_notification_message where text like '%OTOBO\_%';
> +----------+
> | count(*) |
> +----------+
> |      216 |
> +----------+
> 1 row in set (0.002 sec)
> 
> MariaDB [otobo]> 
>

**Comment by bschmalhofer** [comment]
PR was already merged. Closing this issue.
