### ISSUE TITLE
SeleniumTesting: Attachment not shown in CustomerTicketAttachment.t

### ISSUE THREAD

**Issue by bschmalhofer** [RotherOSS/otobo#907]
The attachment tests in _scripts/test/Selenium/Customer/CustomerTicketAttachment.t_ are currently set to TODO. It looks like the attachment is not shown in the customer interface. The cause is not known yet.

![remmina_localhost_localhost_202143-16951,476342](https://user-images.githubusercontent.com/46019/113484301-d6da1d80-94a7-11eb-8280-297479c731c8.png)

**Comment by svenoe** [comment]
The attachments can be downloaded (only from the article directly currently), but the whole layout changed severely, so it's the test which has to be adapted.

The ugly name in the article list is due to it being to long and a missing "overflow: hidden". This needs some fiddling, though - I will postpone this issue.

**Comment by bschmalhofer** [comment]
Adapted the selector for the download link. Click on the paperclip first. 
Closing this issue.
